version: '3'
services:
  app:
      container_name: airbnb
      #image: "node-airbnb:test"
      build:
        context: .
        dockerfile: ./node.Dockerfile
      ports:
        - "5000:5000"
      links:
        - db
      networks:
        - backend
      
  nginx:
      container_name: nginx
      #image: "nginx:test"
      build:
        context: .
        dockerfile: ./nginx.Dockerfile
      ports:
       - "8080:8080"
      networks:
       - backend
      depends_on:
        - app
  db:
    container_name: airbnbDB
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    # volumes:
    #  - "airbnb:/var/lib/mysql"
    restart: always
    # ports:
    #  - 3300:3306
    environment:
      MYSQL_DATABASE: "airbnb"
      #MYSQL_USER: "root"
      #MYSQL_PASSWORD: "rootUser1Go!"
      MYSQL_ROOT_PASSWORD: "rootUser1Go!"
    networks:
      - backend

  redis:
    container_name: airbnbRedis
    image: redis:5.0.6-alpine
    ports:
      - "6379:6379"
    #volumes:
    #  - airbnb:/data/redis
    restart: always
    networks:
      - backend
 
networks: # 가장 기본적인 bridge 네트워크
  backend:
    driver: bridge

#volumes: airbnb: